# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_date', models.DateField(max_length=200)),
                ('place', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_date', models.DateField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunchy.Person'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='persons',
            field=models.ManyToManyField(to='lunchy.Person'),
        ),
    ]
