# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='detail',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='user@domain.com', max_length=254),
        ),
    ]
