# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchy', '0002_auto_20160717_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
