# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchy', '0005_auto_20160720_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
