# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchy', '0006_appointment_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
