# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchy', '0007_auto_20160723_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
