# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchy', '0008_person_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fbid',
            field=models.BigIntegerField(null=True),
        ),
    ]
